// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt-sdaK5eOKyYMtANpx_gM1TSLN0bDPeI',
    appId: '1:506690308404:web:996eb69042a686aa6abd61',
    messagingSenderId: '506690308404',
    projectId: 'voyage-fcddf',
    authDomain: 'voyage-fcddf.firebaseapp.com',
    storageBucket: 'voyage-fcddf.firebasestorage.app',
    measurementId: 'G-6HETRWMVEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSAZBp3v2cLXxDDbgzLNq5panp3ld6Xr8',
    appId: '1:506690308404:android:5fcc85570a72e4546abd61',
    messagingSenderId: '506690308404',
    projectId: 'voyage-fcddf',
    storageBucket: 'voyage-fcddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QbuQoJ6lPs4EVBVlyzjd2F0uztlXVZk',
    appId: '1:506690308404:ios:43697037a2d4b7806abd61',
    messagingSenderId: '506690308404',
    projectId: 'voyage-fcddf',
    storageBucket: 'voyage-fcddf.firebasestorage.app',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt-sdaK5eOKyYMtANpx_gM1TSLN0bDPeI',
    appId: '1:506690308404:web:cc9d568884ec43e86abd61',
    messagingSenderId: '506690308404',
    projectId: 'voyage-fcddf',
    authDomain: 'voyage-fcddf.firebaseapp.com',
    storageBucket: 'voyage-fcddf.firebasestorage.app',
    measurementId: 'G-3MK38F8DV4',
  );
}
